name: ESP32

permissions:
  contents: write

on:
  push:
    tags:
     - 'v*'
  schedule:
     - cron: '0 0 * * 0'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3
      
    - name: Clonar Micropython
      run: git clone --recurse-submodules https://github.com/micropython/micropython.git
    
    - name: Clonar st7789
      run: git clone https://github.com/russhughes/st7789_mpy.git
      
    - name: Instalar dependencias
      run: |
       sudo apt-get update
       sudo apt-get install -y build-essential git wget flex bison gperf pkg-config python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

    - name: Clonar ESP-IDF
      run: |
        mkdir -p esp
        cd esp
        git clone -b v5.2.2 --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf/tools
        python3 idf_tools.py install cmake
        cd ..
        ./install.sh esp32
        cd
        
    - name: Compile with St7789
     # continue-on-error: true
      run: |
        source esp/esp-idf/export.sh
        cd micropython/
        make -C mpy-cross
        export IDF_TARGET=esp32
        cd ports/esp32/
        cp ${GITHUB_WORKSPACE}/st7789_mpy/fonts/bitmap/vga1_16x16.py modules
        cp ${GITHUB_WORKSPACE}/st7789_mpy/fonts/truetype/NotoSans_32.py modules
        cp ${GITHUB_WORKSPACE}/st7789_mpy/fonts/vector/scripts.py modules
        idf.py \
          -D MICROPY_BOARD_DIR="$GITHUB_WORKSPACE/micropython/ports/esp32/boards/" \
          -D USER_C_MODULES="$GITHUB_WORKSPACE/micropython.cmake" \
          -D FROZEN_MPY_DIR="$UPYDIR/modules" \
          -B build
      # -D MICROPY_FROZEN_MANIFEST="" \
    
    - name: Move binaries ST7789
     # if: success() || failure()
      run: |
        mkdir -p ./artifacts
        cp ${GITHUB_WORKSPACE}micropython/ports/esp32/build-ESP32_GENERIC/micropython.bin ./artifacts/
        cp ${GITHUB_WORKSPACE}micropython/ports/esp32/build-ESP32_GENERIC/bootloader/bootloader.bin ./artifacts/
        cp ${GITHUB_WORKSPACE}micropython/ports/esp32/build-ESP32_GENERIC/partition_table/partition-table.bin ./artifacts/
    
    - name: Generate Tag
      id: tag
      run: echo "TAG_NAME=release-$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
      
    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: ${{ env.TAG_NAME }}  # Usa el nombre del tag generado
        title: "Release for version ${{ env.TAG_NAME }}"
        files: ./artifacts/*
